--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/nixxo/Pictures/bgs/wallhaven-85qd7y.png"

-- Special
background="#0a0a0c"
foreground="#bec5c9"
cursor="#bec5c9"

-- Colors
color0="#0a0a0c"
color1="#576061"
color2="#8B755C"
color3="#487089"
color4="#598EA7"
color5="#70B5CB"
color6="#7EC0D4"
color7="#bec5c9"
color8="#85898c"
color9="#576061"
color10="#8B755C"
color11="#487089"
color12="#598EA7"
color13="#70B5CB"
color14="#7EC0D4"
color15="#bec5c9"
