#!/usr/bin/env bash
#   █████╗ ███╗   ██╗██████╗ ██████╗  ██████╗ ██╗██████╗
#  ██╔══██╗████╗  ██║██╔══██╗██╔══██╗██╔═══██╗██║██╔══██╗
#  ███████║██╔██╗ ██║██║  ██║██████╔╝██║   ██║██║██║  ██║
#  ██╔══██║██║╚██╗██║██║  ██║██╔══██╗██║   ██║██║██║  ██║
#  ██║  ██║██║ ╚████║██████╔╝██║  ██║╚██████╔╝██║██████╔╝
#  ╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝╚═════╝  gh0stzk, modified by nixxo (https://github.com/nixxoq)
#                                                         https://github.com/gh0stzk/dotfiles, https://github.com/nixxoq/dotfiles
#  ███╗   ███╗ ██████╗ ██╗   ██╗███╗   ██╗████████╗       21.08.2024 18:50 (UTC +3)
#  ████╗ ████║██╔═══██╗██║   ██║████╗  ██║╚══██╔══╝       Mount and unmount Android device using simple-mtpfs and Rofi
#  ██╔████╔██║██║   ██║██║   ██║██╔██╗ ██║   ██║
#  ██║╚██╔╝██║██║   ██║██║   ██║██║╚██╗██║   ██║
#  ██║ ╚═╝ ██║╚██████╔╝╚██████╔╝██║ ╚████║   ██║
#  ╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═══╝   ╚═╝

BASE_MOUNT_POINT="$HOME/Android_Mount"
ROFI_THEME="$HOME/.config/bspwm/src/rofi-themes/Android.rasi"

list_devices() { simple-mtpfs -l | awk -F': ' '{print $1 " " $2}' | rofi -dmenu -p "Select device" -theme "$ROFI_THEME"; }

is_mounted() { mount | grep "$1" >/dev/null; }

mount_device() {
	DEVICE_NUM=$1
	MOUNT_POINT=$2
	TEXT=""

	[ ! -d "$MOUNT_POINT" ] && mkdir -p "$MOUNT_POINT"

	if simple-mtpfs --device "$DEVICE_NUM" "$MOUNT_POINT"; then
		TEXT="Android device $DEVICE_NUM mounted at $MOUNT_POINT"
	else
		TEXT="Failed to mount Android device $DEVICE_NUM"
	fi

	dunstify --icon=android-sdk --appname=Android --urgency=normal "Android Mount" $TEXT
}

unmount_device() {
	MOUNT_POINT=$1
	TEXT=""

	if fusermount -u "$MOUNT_POINT"; then
		TEXT="Android device unmounted from $MOUNT_POINT"
		rmdir "$MOUNT_POINT"
	else
		TEXT="Failed to unmount Android device"
	fi

	dunstify --icon=android-sdk --appname=Android --urgency=normal "Android Unmount" $TEXT
}

DEVICE=$(list_devices)
DEVICE_NUM=$(echo "$DEVICE" | awk '{print $1}')
DEVICE_NAME=$(echo "$DEVICE" | awk '{$1=""; print $0}' | xargs) # Remove the leading number and trim whitespace
MOUNT_POINT="$BASE_MOUNT_POINT/$DEVICE_NAME"

if [ -z "$DEVICE_NUM" ]; then
	dunstify --icon=android-sdk --appname=Android --urgency=normal "Android Mount" "No device selected"
	exit 1
fi

if is_mounted "$MOUNT_POINT"; then
	ACTION=$(echo "Unmount" | rofi -dmenu -p "$DEVICE_NAME is mounted" -theme "$ROFI_THEME")

	[ "$ACTION" == "Unmount" ] && unmount_device "$MOUNT_POINT"
else
	ACTION=$(echo "Mount" | rofi -dmenu -p "$DEVICE_NAME is not mounted" -theme "$ROFI_THEME")

	[ "$ACTION" == "Mount" ] && mount_device "$DEVICE_NUM" "$MOUNT_POINT"
fi
