#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#	Script to control prefered apps to launch for all themes
#	Author: z0mbi3
#	url:    https://github.com/gh0stzk/dotfiles

WIDGET_DIR="$HOME/.config/bspwm/eww"

declare -A commands=(
    ["--menu"]="rofi -show drun -theme \"$HOME/.config/bspwm/src/rofi-themes/Launcher.rasi\""
    ["--rice"]="RiceSelector"
    ["--terminal"]="Term --terminal"
    ["--floating"]="Term --floating"
    ["--update"]="Term --update"
    ["--checkupdates"]="Term --checkupdates"
    ["--netmanager"]="NetManagerDM"
    ["--bluetooth"]="rofi-bluetooth"
    ["--clipboard"]="rofi -modi \"clipboard:greenclip print\" -theme \"$HOME/.config/bspwm/src/rofi-themes/Clipboard.rasi\" -show clipboard -run-command '{cmd}'"
    ["--screenshot"]="ScreenShoTer"
    ["--powermenu"]="PowerMenu"
    ["--android"]="AndroidMount"
    ["--ranger"]="Term --ranger"
    ["--nvim"]="Term --nvim"
    ["--music"]="Term --music"
    ["--filemanager"]="thunar"
    ["--browser"]="firefox"
    ["--editor"]="geany"
    ["--whats"]="whatsdesk --disable-gpu"
    ["--soundcontrol"]="pavucontrol"
    ["--KeyHelp"]="eww -c \"$WIDGET_DIR\" open --toggle csheet"
    ["--usercard"]="eww -c \"$WIDGET_DIR\" open --toggle launchermenu"
    ["--player"]="eww -c \"$WIDGET_DIR\" open --toggle music"
    ["--calendar"]="eww -c \"$WIDGET_DIR\" open --toggle date"
)

if [[ -n "${commands[$1]}" ]]; then
    eval "${commands[$1]}"
else
    echo "Invalid Option"
fi
