#!/usr/bin/env bash

options=(
    ""
    ""
    ""
    ""
    ""
)

chosen=$(printf "%s\n" "${options[@]}" | rofi -dmenu -p "Goodbye ${USER}" -mesg "Uptime: $(uptime -p | sed -e 's/up //g')" -theme "$HOME"/.config/bspwm/src/rofi-themes/PowerMenu.rasi)

case $chosen in
"")
    systemctl poweroff
    ;;
"")
    systemctl reboot
    ;;
"")
    physlock -d
    ;;
"")
    mpc -q pause
    amixer set Master mute
    systemctl suspend
    ;;
"")
    bspc quit
    ;;
esac
