#!/usr/bin/env bash
#  ███████╗██╗   ██╗███████╗████████╗███████╗███╗   ███╗    ██╗   ██╗ █████╗ ██████╗ ███████╗
#  ██╔════╝╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝████╗ ████║    ██║   ██║██╔══██╗██╔══██╗██╔════╝
#  ███████╗ ╚████╔╝ ███████╗   ██║   █████╗  ██╔████╔██║    ██║   ██║███████║██████╔╝███████╗
#  ╚════██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██║╚██╔╝██║    ╚██╗ ██╔╝██╔══██║██╔══██╗╚════██║
#  ███████║   ██║   ███████║   ██║   ███████╗██║ ╚═╝ ██║     ╚████╔╝ ██║  ██║██║  ██║███████║
#  ╚══════╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝     ╚═╝      ╚═══╝  ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝

CONFIG_FILE="$HOME/.config/bspwm/src/system.ini"
SFILE="$HOME/.config/bspwm/src/.sys"

[[ -f "$SFILE" ]] && echo "Already configured." && exit 0

# Create the configuration file if it doesn't exist
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Creating new configuration file: $CONFIG_FILE"
    cat <<EOL >"$CONFIG_FILE"
[system]
sys_network_interface = not_set
;;sys_network_interface2 = not_set
sys_graphics_card = not_set
sys_battery = not_set
sys_adapter = not_set
EOL
fi

# Function to get and set values
setup_system_vars() {
    declare -A sys_vars=(
        [sys_network_interface]="$(ip -o route get 1 | awk '{print $5; exit}')"
        [sys_graphics_card]="$(basename $(find /sys/class/backlight -maxdepth 1 -type l | head -n1))"
        [sys_battery]="$(basename $(find /sys/class/power_supply -maxdepth 1 -type l -name 'BAT*' | head -n1))"
        [sys_adapter]="$(basename $(find /sys/class/power_supply -maxdepth 1 -type l -name 'A[CD]*' | head -n1))"
    )

    for var in "${!sys_vars[@]}"; do
        [[ -n "${sys_vars[$var]}" ]] && sed -i "s/$var = .*/$var = ${sys_vars[$var]}/" "$CONFIG_FILE" || echo "Failed to update $var"
    done
}

# Run the setup function
setup_system_vars

# Create the .sys file to indicate that the configuration has been done
touch "$SFILE"
