#!/usr/bin/env bash
#  ╔═╗╦═╗╔═╗╦ ╦  ╦ ╦╔═╗╔╦╗╔═╗╔╦╗╔═╗╔═╗
#  ╠═╣╠╦╝║  ╠═╣  ║ ║╠═╝ ║║╠═╣ ║ ║╣ ╚═╗
#  ╩ ╩╩╚═╚═╝╩ ╩  ╚═╝╩  ═╩╝╩ ╩ ╩ ╚═╝╚═╝
# Script to check for new updates in arch and AUR. Copyright 2023 gh0stzk
# Author: z0mbi3, modified by NixxO (https://github.com/nixxoq)
# url: https://github.com/nixxoq/dotfiles

get_total_updates() {
    local total_updates
    total_updates=$(($(checkupdates 2>/dev/null | wc -l || echo 0) + $(paru -Qua 2>/dev/null | wc -l || echo 0)))
    echo "${total_updates:-0}"
}

get_list_updates() {
    echo -e "\033[1m\033[34mRegular updates:\033[0m"
    checkupdates | sed 's/->/\x1b[32;1m\x1b[0m/g'
}

get_list_aur_updates() {
    echo -e "\n\033[1m\033[34mAur updates available:\033[0m"
    paru -Qua | sed 's/->/\x1b[32;1m\x1b[0m/g'
}

print_updates() {
    local print_updates
    print_updates=$(get_total_updates)

    if [[ "$print_updates" -gt 0 ]]; then
        echo -e "\033[1m\033[33mThere are $print_updates updates available:\033[0m\n"
        get_list_updates
        get_list_aur_updates
    else
        echo -e "\033[1m\033[32mYour system is already updated!\033[0m"
    fi
}

update_system() {
    echo -e "\033[1m\033[34mUpdating system...\033[0m"
    
    local print_updates
    print_updates=$(get_total_updates)
    if [[ "$print_updates" -gt 0 ]]; then
        if [[ "$2" == "--ignore-packages" ]]; then
            shift 2
            ignore_packages=""
            for package in "$@"; do
                ignore_packages+="--ignore $package "
            done
            paru -Syyu --combinedupgrade $ignore_packages
        else
            paru -Syyu --combinedupgrade
        fi
    else
        echo -e "\033[1m\033[32mYour system is already updated!\033[0m"
    fi
}

case "$1" in
--get-updates) get_total_updates ;;
--print-updates) print_updates ;;
--update-system) update_system "$@" ;;
--help | *) echo -e "Updates [options]

Options:
	--get-updates		Get the number of updates available.
	--print-updates		Print the number of available package to update.
	--update-system		Update your system including the AUR packages.\n" ;;
esac
