#!/usr/bin/env bash

get_weather() {
    KEY="8b05d62206f459e1d298cbe5844d7d87"
    CITY=$1
    CITYN=$(echo "$CITY" | sed 's/ /%20/g')
    UNITS="metric"
    WEATHER=$(curl -sf "api.openweathermap.org/data/2.5/weather?q=$CITYN&appid=$KEY&units=$UNITS")

    WEATHER_DESC=$(echo "$WEATHER" | jq -r ".weather[0].main")
    WEATHER_TEMP=$(echo "$WEATHER" | jq ".main.temp" | cut -d "." -f 1)
    WEATHER_ICON_CODE=$(echo "$WEATHER" | jq -r ".weather[].icon" | head -1)
    WEATHER_FEELS_LIKE=$(echo "$WEATHER" | jq ".main.feels_like" | cut -d "." -f 1)

    case $WEATHER_ICON_CODE in
    "01d") WEATHER_ICON="" ;;
    "01n") WEATHER_ICON="" ;;
    "02d") WEATHER_ICON="" ;;
    "02n") WEATHER_ICON="" ;;
    "03d" | "03n" | "04d" | "04n") WEATHER_ICON="" ;;
    "09d" | "09n" | "10d" | "10n") WEATHER_ICON="" ;;
    "11d" | "11n") WEATHER_ICON="" ;;
    "13d" | "13n") WEATHER_ICON="" ;;
    "40d" | "40n") WEATHER_ICON="" ;;
    *) WEATHER_ICON="" ;;
    esac
}

command_line_args() {
    CITY="Kyiv"
    args=("$@")
    for arg in "${args[@]}"; do
        case $arg in
        --city=*) CITY="${arg#*=}" ;;
        --city) CITY="${args[1]}" ;;
        esac
    done

    get_weather "$CITY"

    if [[ $# -eq 0 || ! " ${args[@]} " =~ " --show-current-temp " && ! " ${args[@]} " =~ " --show-feels-like " && ! " ${args[@]} " =~ " --show-weather-desc " && ! " ${args[@]} " =~ " --show-icon " && ! " ${args[@]} " =~ " --show-full " && ! " ${args[@]} " =~ " --show-city " ]]; then
        echo -e "\033[1m\033[34mInformation about weather in $CITY:\033[0m"
        echo -e "\033[1m\033[32mTemperature:\033[0m $WEATHER_TEMP°"
        echo -e "\033[1m\033[32mFeels like:\033[0m $WEATHER_FEELS_LIKE°"
        echo -e "\033[1m\033[32mWeather:\033[0m $WEATHER_DESC"
        echo -e "\033[1m\033[32mIcon:\033[0m $WEATHER_ICON"
    fi

    for arg in "${args[@]}"; do
        case $arg in
        "--show-current-temp") echo "$WEATHER_TEMP" ;;
        "--show-feels-like") echo "$WEATHER_FEELS_LIKE" ;;
        "--show-weather-desc") echo "$WEATHER_DESC" ;;
        "--show-icon") echo "$WEATHER_ICON" ;;
        "--show-full") echo "$WEATHER" ;;
        "--show-city") echo "$CITY" ;;
        esac
    done
}

command_line_args "$@"
