exec-once = swww img ~/Pictures/bgs/wallhaven-l8x1pr.jpg &

# USE THIS IF YOU WANT SPLIT MONITOR WORKSPACES!!!
# REQUIRES split-monitor-workspaces plugin (https://github.com/Duckonaut/split-monitor-workspaces)
# plugin {
#     split-monitor-workspaces {
#         count = 4
#         keep_focused = 0
#         enable_notifications = 0
#         enable_persistent_workspaces = 0
#     }
# }

input {
    kb_layout = us,ru,ua  # TODO: customize layouts using my own configurator (confi)
    kb_options = grp:alt_shift_toggle
}

exec-once = hyprctl setcursor Bibata-Modern-Ice 24