# ░█▀▀░▀█▀░█▀█░█▀▄░▀█▀░█░█░█▀█░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀░█▀▀
# ░▀▀█░░█░░█▀█░█▀▄░░█░░█░█░█▀▀░░░█░░░█░█░█░█░█▀▀░░█░░█░█░▀▀█
# ░▀▀▀░░▀░░▀░▀░▀░▀░░▀░░▀▀▀░▀░░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀░▀▀▀


exec-once = waypaper --restore &

input {
    kb_layout = us,ru,ua  # TODO: customize layouts using my own configurator (confi)
    kb_options = grp:alt_shift_toggle
}

exec-once = hyprctl setcursor Bibata-Modern-Ice 24